---
language: ruby
branches:
  only:
    - master
gemfile: .gemfile
notifications:
  email: false
rvm:
  - 2.1.9
  - 2.1.8
  - 2.1.7
  - 2.1.6
  - 1.9.3.551
  - 1.9.3.484
env:
  - PUPPET_VERSION=4.4.2
  - PUPPET_VERSION=4.4.1
  - PUPPET_VERSION=4.3.2
  - PUPPET_VERSION=4.3.1
  - PUPPET_VERSION=4.2.2
  - PUPPET_VERSION=4.2.1
  - PUPPET_VERSION=3.8.7
  - PUPPET_VERSION=3.8.5
  - PUPPET_VERSION=3.8.4
  - PUPPET_VERSION=3.8.2
  - PUPPET_VERSION=3.8.1
  - PUPPET_VERSION=3.8.0
  - PUPPET_VERSION=3.7.4
  - PUPPET_VERSION=3.7.3
  - PUPPET_VERSION=3.7.2
matrix:
  include:
    # https://docs.puppet.com/pe/latest/overview_version_table.html

    # PE 2016.1.2
    - rvm: 2.1.9
      env: PUPPET_VERSION=4.4.2
    # PE 2016.1.1
    - rvm: 2.1.8
      env: PUPPET_VERSION=4.4.1

    # PE 2015.3.2 & 2015.3.3
    - rvm: 2.1.8
      env: PUPPET_VERSION=4.3.2
    # PE 2015.3.0 & 2015.3.1
    - rvm: 2.1.7
      env: PUPPET_VERSION=4.3.1
    # PE 2015.2.3
    - rvm: 2.1.7
      env: PUPPET_VERSION=4.2.3
    # PE 2015.2.1 & 2015.2.2
    - rvm: 2.1.6
      env: PUPPET_VERSION=4.2.2
    # PE 2015.2.0
    - rvm: 2.1.6
      env: PUPPET_VERSION=4.2.1

    # PE 3.8.5
    - rvm: 2.1.7
      env: PUPPET_VERSION=3.8.7
    - rvm: 1.9.3.551
      env: PUPPET_VERSION=3.8.7
    # PE 3.8.4
    - rvm: 2.1.7
      env: PUPPET_VERSION=3.8.5
    - rvm: 1.9.3.551
      env: PUPPET_VERSION=3.8.5
    # PE 3.8.3 & 3.8.3.1
    - rvm: 2.1.7
      env: PUPPET_VERSION=3.8.4
    - rvm: 1.9.3.551
      env: PUPPET_VERSION=3.8.4
    # PE 3.8.2 & 3.8.2.1
    - rvm: 2.1.6
      env: PUPPET_VERSION=3.8.2
    - rvm: 1.9.3.551
      env: PUPPET_VERSION=3.8.2
    # PE 3.8.1
    - rvm: 2.1.6
      env: PUPPET_VERSION=3.8.1
    - rvm: 1.9.3.551
      env: PUPPET_VERSION=3.8.1
    # PE 3.8.0
    - rvm: 1.9.3.551
      env: PUPPET_VERSION=3.8.0

    # PE 3.7.2
    - rvm: 1.9.3.484
      env: PUPPET_VERSION=3.7.4
    # PE 3.7.1
    - rvm: 1.9.3.484
      env: PUPPET_VERSION=3.7.3
    # PE 3.7.0
    - rvm: 1.9.3.484
      env: PUPPET_VERSION=3.7.2
